### ISSUE TITLE
Mousewheel moves the sun/moon but does not change time

### ISSUE THREAD

**Issue by YugoNumachi** [unsoluble/smalltime#22]
Using the scroll wheel over the sun/moon area effectively moves the sun/moon but the change is not taken into account and the time of day is not changed.

**Comment by unsoluble** [comment]
Oh interesting, never thought to try that. Will investigate! :)

**Comment by unsoluble** [comment]
Hmm. What browser/OS are you using? Scrolling the slider works fine for me here, in the Foundry app, Chrome, and Firefox on macOS.

**Comment by unsoluble** [comment]
Ah, found it. Fixed in https://github.com/unsoluble/smalltime/commit/f841920263af3fd508b0537a6424615df57171f9

**Comment by YugoNumachi** [comment]
In version 1.4.1, with all other modules disabled, the issue remains, don't know if the pull request is part of this release.

**Comment by unsoluble** [comment]
Yeah that commit isn't in a release yet. You can grab the smalltime.js file from it if you want to get it now tho.
